# Generated by Django 5.0.4 on 2024-05-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Activo'), ('pending', 'Pendiente'), ('in-active', 'Inactivo')], default='in-active', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer'), ('other', 'Otro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('national_id_card', 'INE'), ('drivers_licence', 'Licencia de conducir'), ('international_passport', 'Pasaporte')], max_length=140),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marrital_status',
            field=models.CharField(choices=[('married', 'Casado'), ('single', 'Soltero'), ('other', 'Otro')], max_length=40),
        ),
    ]
