# Generated by Django 5.0.4 on 2024-05-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_status_alter_kyc_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='nationality',
        ),
    ]
