# Generated by Django 5.0.4 on 2024-05-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_kyc_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marrital_status',
            field=models.CharField(choices=[('married', 'Casado'), ('single', 'Soltero')], max_length=40),
        ),
    ]
