# Generated by Django 5.0.4 on 2024-05-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='fax',
        ),
    ]
