# Generated by Django 5.0.4 on 2024-05-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_kyc_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='nationality',
        ),
    ]
