# Generated by Django 5.0.4 on 2024-05-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_kyc_date_of_birth_alter_kyc_marrital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
