# Generated by Django 5.0.4 on 2024-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_kyc_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='identity_image',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='identity_type',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='signature',
        ),
        migrations.AddField(
            model_name='kyc',
            name='company',
            field=models.CharField(choices=[('AB FORTI', 'AB FORTI'), ('INNOVET', 'INNOVET'), ('UPPER LOGISTICS', 'UPPER LOGISTICS'), ('BE EXEN', 'BE EXEN')], default='AB FORTI', max_length=50),
        ),
    ]
