# Generated by Django 5.0.4 on 2024-05-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_kyc_fax_remove_kyc_identity_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='mobile',
        ),
    ]
