# Generated by Django 5.0.4 on 2024-05-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_kyc_full_name_kyc_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(max_length=1000),
        ),
    ]
