# Generated by Django 5.0.4 on 2024-05-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_kyc_mobile_alter_kyc_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='full_name',
        ),
    ]
