# Generated by Django 5.0.4 on 2024-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'Fallido'), ('completed', 'Completado'), ('pending', 'Pendiente'), ('processing', 'Procesando'), ('requested', 'Solicitado')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('trasnfer', 'Transferir'), ('recieved', 'Recivir'), ('withdraw', 'Retirar'), ('refund', 'Reembolso'), ('request', 'Peticion'), ('none', 'Ninguno')], default='none', max_length=100),
        ),
    ]
