# Generated by Django 5.0.4 on 2024-05-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evidencewithpersons_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencewithpersons',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
