# Generated by Django 5.0.4 on 2024-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('completed', 'completed'), ('pending', 'pending'), ('processing', 'processing'), ('requested', 'requested'), ('request_sent', 'requested sent'), ('request_settled', 'request settled'), ('request_processing', 'request processing')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('trasnfer', 'Transferir'), ('recieved', 'Recivir'), ('withdraw', 'Retirar'), ('refund', 'Reembolso'), ('request', 'Payment Request'), ('none', 'Ninguno')], default='none', max_length=100),
        ),
    ]
