# Generated by Django 5.0.4 on 2024-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_evidencewithpersons_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencewithpersons',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
