# Generated by Django 5.0.4 on 2024-05-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_mounth_creditcard_mo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='mo',
            new_name='month',
        ),
    ]
