# Generated by Django 5.0.4 on 2024-05-29 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_evidencewithpersons_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencewithpersons',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
