# Generated by Django 5.0.4 on 2024-05-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
