# Generated by Django 5.0.4 on 2024-05-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_evidencewithpersons_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencewithpersons',
            name='admin_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
