# Generated by Django 5.0.4 on 2024-05-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evidence_ticket_delete_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='check_hoto',
            new_name='check_photo',
        ),
    ]
