# Generated by Django 5.0.4 on 2024-05-23 18:17

import shortuuid.django_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_check_hoto_evidence_check_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=4, prefix='217', unique=True),
        ),
    ]
