# Generated by Django 5.0.4 on 2024-05-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_evidencewithpersons_admin_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencewithpersons',
            name='admin_deposit',
        ),
    ]
