# Generated by Django 5.0.4 on 2024-05-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_evidence_id_alter_ticket_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='check_photo',
            new_name='reviewed',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='date_upload',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='evidence',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='photo',
            field=models.ImageField(upload_to='evidences/'),
        ),
    ]
